image: cirrusci/flutter:latest

stages:
  - build

flutter_build:
  stage: build
  before_script:
    - flutter clean
    - flutter packages get
  script:
    - flutter build apk --debug
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-debug.apk
    expire_in: 1 day