// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart/' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ99ACOnYuIay-3VQHXof4Wgxn5_XzXrc',
    appId: '1:334748235159:web:3290860ab427ab7bb400d2',
    messagingSenderId: '334748235159',
    projectId: 'flutterapp-9075d',
    authDomain: 'flutterapp-9075d.firebaseapp.com',
    storageBucket: 'flutterapp-9075d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU_CLfMr_K3yjN6Lb8K-NnVDFcN3JgV9k',
    appId: '1:334748235159:android:4c7043b09802cb03b400d2',
    messagingSenderId: '334748235159',
    projectId: 'flutterapp-9075d',
    storageBucket: 'flutterapp-9075d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnz9viSoA7B5q_EIhWfovqQq6LPbP6xaM',
    appId: '1:334748235159:ios:422f3fb7be6c733ab400d2',
    messagingSenderId: '334748235159',
    projectId: 'flutterapp-9075d',
    storageBucket: 'flutterapp-9075d.appspot.com',
    iosClientId: '334748235159-lokpki9jg1al38vblc5bge3sn7svcjd7.apps.googleusercontent.com',
    iosBundleId: 'kg.aalyev.flutterapp',
  );
}
